### ISSUE TITLE
Add local models, supervisor process

### ISSUE THREAD

**Issue by matildepark** [hdresearch/nolita#46]
If a user doesn't even know how to use a model or anything, we should help custody and supervise an Ollama process and use it as a fallback option. There's a few projects that already do this. Function calling may be an issue. Worth investigating. Likely intersects with moving off llm-api (#16, #5).

**Comment by matildepark** [comment]
See https://github.com/hdresearch/nolita/blob/ty/replace-zod-gpt/src/agent/llamaCompletion.ts

**Comment by AlephNotation** [comment]
closed by #124
