### ISSUE TITLE
headless flag doesn't seem to do anything

### ISSUE THREAD

**Issue by harperreed** [hdresearch/nolita#59]
`npx nolita` doesn't respect the headless flag (either by `--headless`, setting the `HDR_HEADLESS` env var, or setting it in the config). It just runs the process headless regardless of whether the flag is true or false.

**Comment by matildepark** [comment]
I'll double check the logic in bin real quick.

**Comment by harperreed** [comment]
i may be making a mistake. just want to double check that it is doing what it is saying it is doing (i think it is)

**Comment by matildepark** [comment]
We're preparing to release 2.0 on stable within the next week but once #60 merges you can run `npx nolita@alpha` to run this normally. It's just boring JavaScript type coercion shenanigans. Thank you for spotting this.

**Comment by harperreed** [comment]
ok great! will try it then
